// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuCzC4th05rpuFkJ3ld6I-HyKRBE751P4',
    appId: '1:725797507137:web:e1368993c8c92ca87876c0',
    messagingSenderId: '725797507137',
    projectId: 'flutter-firebase-trainin-a5d7c',
    authDomain: 'flutter-firebase-trainin-a5d7c.firebaseapp.com',
    storageBucket: 'flutter-firebase-trainin-a5d7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgnZU00O7_-KT_LXbOfYee50dgQCrAmw',
    appId: '1:725797507137:android:fefd000d4f96568d7876c0',
    messagingSenderId: '725797507137',
    projectId: 'flutter-firebase-trainin-a5d7c',
    storageBucket: 'flutter-firebase-trainin-a5d7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZupIj8yHn0i_PyUhIVqObb9dYwT-ixcE',
    appId: '1:725797507137:ios:541654ce8c83661f7876c0',
    messagingSenderId: '725797507137',
    projectId: 'flutter-firebase-trainin-a5d7c',
    storageBucket: 'flutter-firebase-trainin-a5d7c.firebasestorage.app',
    androidClientId: '725797507137-0faltrbe3sea18ghkldp0mgtso2lqr5n.apps.googleusercontent.com',
    iosClientId: '725797507137-u6pttat2mpua14vjv2t4pun4dj0tj90u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudFirestoreFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZupIj8yHn0i_PyUhIVqObb9dYwT-ixcE',
    appId: '1:725797507137:ios:541654ce8c83661f7876c0',
    messagingSenderId: '725797507137',
    projectId: 'flutter-firebase-trainin-a5d7c',
    storageBucket: 'flutter-firebase-trainin-a5d7c.firebasestorage.app',
    androidClientId: '725797507137-0faltrbe3sea18ghkldp0mgtso2lqr5n.apps.googleusercontent.com',
    iosClientId: '725797507137-u6pttat2mpua14vjv2t4pun4dj0tj90u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudFirestoreFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuCzC4th05rpuFkJ3ld6I-HyKRBE751P4',
    appId: '1:725797507137:web:5b588882e9e8bd787876c0',
    messagingSenderId: '725797507137',
    projectId: 'flutter-firebase-trainin-a5d7c',
    authDomain: 'flutter-firebase-trainin-a5d7c.firebaseapp.com',
    storageBucket: 'flutter-firebase-trainin-a5d7c.firebasestorage.app',
  );
}
